name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release

          ### Features
          - AI-powered 3D model generation from text
          - Real-time 3D preview
          - STL/OBJ/PLY export

          ### Installation
          See README.md for installation instructions

          ### Docker
          ```bash
          docker pull ${{ secrets.DOCKER_USERNAME }}/ai-3d-generator:${{ github.ref }}
          ```
        draft: false
        prerelease: false

    - name: Upload Release Assets
      run: |
        # Create release artifacts
        zip -r ai-3d-generator-${{ github.ref }}.zip . -x "*.git*" "venv/*" "node_modules/*"